language: perl

os:
  - linux
  # - osx

# services:
  # - docker

perl:
  - "5.24"
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"

install:
  - cpanm --skip-satisfied --quiet --notest Sendmail::PMilter Data::Validate::IP Net::DNS Geo::IP Net::Whois::IP Net::Whois::IANA Locale::Country CHI IPC::SysV B::Lint IPC::System::Simple warnings::unused Sys::Hostname::FQDN Sys::Syslog

script:
  - perl -MO=Lint cmilter
  - perl -c -Mwarnings::unused cmilter
