os:
  - linux
  - osx
language: perl
perl:
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
install:
  - cpanm --quiet --installdeps --notest Sendmail::PMilter Data::Validate::IP Net::DNS Geo::IP Net::Whois::IP Net::Whois::IANA Locale::Country CHI IPC::SysV
  - cpanm --quiet --notest Sendmail::PMilter Data::Validate::IP Net::DNS Geo::IP Net::Whois::IP Net::Whois::IANA Locale::Country CHI IPC::SysV
  - perl -c cmilter
